// @component PrintableCampaign — Print-optimized campaign view for PDF export
"use client";

import React, { useRef, useCallback } from "react";
import { useReactToPrint } from "react-to-print";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import {
  getChannelLabel,
  getAudienceLabel,
  formatDate,
  buildDeliverableCopyText,
} from "@/components/campaign-detail/helpers";

// ── Types ─────────────────────────────────────────────────────────────

interface AudienceNarrative {
  hook: string;
  framing: string;
  key_stat: string;
  call_to_action: string;
  tone: string;
}

interface Analysis {
  research_summary: string | null;
  key_messages: string[] | null;
  fw_values_lead: string | null;
  fw_causal_chain: string | null;
  fw_solutions_framing: string | null;
  fw_thematic_bridge: string | null;
  fw_cultural_freight: string | null;
  audience_narratives: Record<string, AudienceNarrative> | null;
}

interface ChannelRow {
  id: string;
  channel: string;
  audience_segment: string;
  stage: string;
  status: string;
  week_number: number | null;
  scheduled_date: string | null;
  suggested_content: string | null;
  narrative_angle: string | null;
  hashtags: string[] | null;
  mentions: string[] | null;
  call_to_action: string | null;
  media_suggestion: string | null;
  char_limit: number | null;
  key_message_ids: number[] | null;
  publish_order: number | null;
}

interface PrintableCampaignProps {
  campaign: {
    title: string;
    status?: string;
    research_authors?: string[] | null;
    publication_date?: string | null;
  };
  analysis: Analysis | null;
  channels: ChannelRow[];
}

const MESSAGING_FIELDS = [
  { key: "fw_values_lead" as const, label: "Values Lead" },
  { key: "fw_causal_chain" as const, label: "Causal Chain" },
  { key: "fw_solutions_framing" as const, label: "Solutions Framing" },
  { key: "fw_thematic_bridge" as const, label: "Thematic Bridge" },
  { key: "fw_cultural_freight" as const, label: "Cultural Freight" },
];

// ── Print Content ─────────────────────────────────────────────────────

const PrintContent = React.forwardRef<HTMLDivElement, PrintableCampaignProps>(
  function PrintContent({ campaign, analysis, channels }, ref) {
    const narratives = (analysis?.audience_narratives || {}) as Record<
      string,
      AudienceNarrative
    >;
    const narrativeEntries = Object.entries(narratives);

    // Group channels by week
    const weekGroups: Record<number, ChannelRow[]> = {};
    channels.forEach((ch) => {
      const week = ch.week_number ?? 0;
      if (!weekGroups[week]) weekGroups[week] = [];
      weekGroups[week].push(ch);
    });
    const sortedWeeks = Object.keys(weekGroups)
      .map(Number)
      .sort((a, b) => a - b);

    return (
      <div ref={ref} className="print-content">
        {/* Header */}
        <div className="print-header">
          <h1 className="print-title">{campaign.title}</h1>
          {campaign.research_authors && campaign.research_authors.length > 0 && (
            <p className="print-authors">
              {campaign.research_authors.join(", ")}
            </p>
          )}
          {campaign.publication_date && (
            <p className="print-date">
              Published {formatDate(campaign.publication_date)}
            </p>
          )}
          <p className="print-branding">
            Generated by Meridian — Northwestern IPR
          </p>
        </div>

        {/* Strategy Section */}
        {analysis && (
          <>
            <h2 className="print-section-title">Strategy</h2>

            {/* Research Summary */}
            {analysis.research_summary && (
              <div className="print-block">
                <h3 className="print-block-title">Research Summary</h3>
                <p className="print-text">{analysis.research_summary}</p>
              </div>
            )}

            {/* Key Messages */}
            {analysis.key_messages && analysis.key_messages.length > 0 && (
              <div className="print-block">
                <h3 className="print-block-title">Key Messages</h3>
                <ol className="print-list">
                  {analysis.key_messages.map((msg, i) => (
                    <li key={i}>{msg}</li>
                  ))}
                </ol>
              </div>
            )}

            {/* Messaging Guidance */}
            <div className="print-block">
              <h3 className="print-block-title">Messaging Guidance</h3>
              {MESSAGING_FIELDS.map(({ key, label }) => {
                const value = analysis[key];
                if (!value) return null;
                return (
                  <div key={key} className="print-subblock">
                    <h4 className="print-sublabel">{label}</h4>
                    <p className="print-text">{value}</p>
                  </div>
                );
              })}
            </div>

            {/* Audience Narratives */}
            {narrativeEntries.length > 0 && (
              <div className="print-block page-break-before">
                <h3 className="print-block-title">Audience Narratives</h3>
                {narrativeEntries.map(([audience, narrative]) => (
                  <div key={audience} className="print-narrative">
                    <h4 className="print-audience-label">
                      {getAudienceLabel(audience)}
                    </h4>
                    <div className="print-narrative-grid">
                      <div>
                        <span className="print-field-label">Hook</span>
                        <p className="print-text">{narrative.hook}</p>
                      </div>
                      <div>
                        <span className="print-field-label">Framing</span>
                        <p className="print-text">{narrative.framing}</p>
                      </div>
                      <div>
                        <span className="print-field-label">Key Stat</span>
                        <p className="print-text">{narrative.key_stat}</p>
                      </div>
                      <div>
                        <span className="print-field-label">Call to Action</span>
                        <p className="print-text">{narrative.call_to_action}</p>
                      </div>
                      <div>
                        <span className="print-field-label">Tone</span>
                        <p className="print-text">{narrative.tone}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </>
        )}

        {/* Campaign Plan Section */}
        {channels.length > 0 && (
          <>
            <h2 className="print-section-title page-break-before">
              Campaign Plan
            </h2>

            {sortedWeeks.map((week) => (
              <div key={week} className="print-week">
                <h3 className="print-week-title">
                  {week === 0 ? "Unscheduled" : `Week ${week}`}
                  <span className="print-week-count">
                    {" "}
                    — {weekGroups[week].length} deliverable
                    {weekGroups[week].length !== 1 ? "s" : ""}
                  </span>
                </h3>

                {weekGroups[week].map((ch) => {
                  const copyText = buildDeliverableCopyText(ch);
                  return (
                    <div key={ch.id} className="print-deliverable">
                      <div className="print-deliverable-header">
                        <strong>{getChannelLabel(ch.channel)}</strong>
                        <span className="print-meta">
                          {getAudienceLabel(ch.audience_segment)} · {ch.stage}{" "}
                          · {ch.status}
                          {ch.scheduled_date &&
                            ` · ${formatDate(ch.scheduled_date)}`}
                        </span>
                      </div>

                      {ch.suggested_content && (
                        <div className="print-content-box">
                          <p className="print-text whitespace-pre-wrap">
                            {copyText}
                          </p>
                        </div>
                      )}

                      <div className="print-deliverable-meta">
                        {ch.narrative_angle && (
                          <div>
                            <span className="print-field-label">
                              Narrative Angle
                            </span>
                            <p className="print-text">{ch.narrative_angle}</p>
                          </div>
                        )}
                        {ch.call_to_action && (
                          <div>
                            <span className="print-field-label">
                              Call to Action
                            </span>
                            <p className="print-text">{ch.call_to_action}</p>
                          </div>
                        )}
                        {ch.media_suggestion && (
                          <div>
                            <span className="print-field-label">
                              Media Suggestion
                            </span>
                            <p className="print-text">{ch.media_suggestion}</p>
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            ))}
          </>
        )}
      </div>
    );
  }
);

// ── Export Button + Hidden Print Content ───────────────────────────────

export function PrintableCampaign({
  campaign,
  analysis,
  channels,
}: PrintableCampaignProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const handlePrint = useReactToPrint({
    contentRef,
    documentTitle: `${campaign.title} — Meridian`,
  });

  const onPrint = useCallback(() => {
    handlePrint();
  }, [handlePrint]);

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        className="gap-1.5"
        onClick={onPrint}
      >
        <Download className="h-3.5 w-3.5" />
        Download PDF
      </Button>

      {/* Hidden print content — only visible when printing */}
      <div className="hidden print:block">
        <PrintContent
          ref={contentRef}
          campaign={campaign}
          analysis={analysis}
          channels={channels}
        />
      </div>
    </>
  );
}
